package com.mtv.app.shopme.common

object ConstantPreferences {
    const val USER_ACCOUNT = "USER_ACCOUNT"
    const val PROFILE_PHOTO_STRING = "PROFILE_PHOTO_STRING"
    const val FCM_STATUS = "FCM_STATUS"
    const val FCM_TOKEN = "FCM_TOKEN"
    const val FCM_CUSTOMER_NOTIFICATION = "FCM_CUSTOMER_NOTIFICATION"
    const val FCM_SELLER_NOTIFICATION = "FCM_SELLER_NOTIFICATION"
    const val ACCESS_TOKEN = "ACCESS_TOKEN"
    const val USER_ROLE = "USER_ROLE"
    const val REMEMBERED_LOGIN_EMAIL = "REMEMBERED_LOGIN_EMAIL"
    const val SPLASH_RESPONSE = "SPLASH_RESPONSE"
    const val CUSTOMER_RESPONSE = "CUSTOMER_RESPONSE"
}
